<?php 
 return [
    [
        'name'=>'Abuja (FCT) State',
        'cities'=>[
            'Central Business Dis',
            'Gwarinpa',
            'Kubwa',
            'Wuse',
            'Wuse 2',
            'Abaji',
            'Apo District',
            'Asokoro',
            'Bwari',
            'Dakibiyu',
            'Dakwo District',
            'Dei-Dei',
            'Duboyi',
            'Durumi',
            'Dutse-Alhaji',
            'Gaduwa',
            'Galadimawa',
            'Garki 1',
            'Garki 2',
            'Gudu',
            'Guzape District',
            'Gwagwa',
            'Gwagwalada',
            'Idu Industrial',
            'Jabi',
            'Jahi',
            'Jikwoyi',
            'Jiwa',
            'Kabusa',
            'Kado',
            'Karmo',
            'Karshi',
            'Karu',
            'Katampe',
            'Kaura',
            'Kpeyegyi',
            'Kuchigoro',
            'Kuje',
            'Kurudu',
            'Kwali',
            'Lokogoma',
            'Lugbe District',
            'Mabushi',
            'Maitama',
            'Mararaba',
            'Masaka',
            'Mbora',
            'Mpape',
            'Nyanya',
            'Okanje',
            'Orozo',
            'Pyakasa',
            'Sobo Gida',
            'Utako',
            'Wumba',
            'Wuye',
            'Zuba'
        ]
    ],
    [
        'name'=>'Lagos State',
        'cities'=>[     
            'Ajah',
            'Amuwo-Odofin',
            'Ikeja',
            'Ojo',
            'Surulere',
            'Abule Egba',                   
            'Agbara-Igbesan',                     
            'Agboyi/Ketu',                     
            'Agege',                     
            'Alimosho',                     
            'Apapa',                     
            'Badagry',                    
            'Egbe Idimu',                     
            'Ejigbo',                     
            'Eko Atlantic',                     
            'Epe',                     
            'Gbagada',                     
            'Ibeju',                     
            'Ifako-Ijaiye',                     
            'Ikorodu',                     
            'Ikotun/Igando',                     
            'Ikoyi',                     
            'Ilashe',                     
            'Ilupeju',                     
            'Ipaja',                    
            'Isolo',                     
            'Kosofe',                     
            'Lagos Island (Eko)',                     
            'Lekki',                     
            'Magodo',                     
            'Maryland',                     
            'Mushin',                     
            'Ogba',                     
            'Ogudu',                     
            'Ojodu',                     
            'Ojota',                    
            'Orile',                    
            'Oshodi',                     
            'Shomolu',                     
            'Tarkwa Bay Island',                     
            'Victoria Island',                     
            'Yaba',
        ]
    ],
    [
        'name'=>'Ogun State',
        'cities'=>[
            'Abeokuta North',
            'Abeokuta South',
            'Ado-Odo/Ota',
            'Ijebu Ode',
            'Obafemi-Owode',
            'Ayetoro',
            'Ewekoro',
            'Ifo',
            'Ijebu',
            'Ikenne',
            'Ilaro',
            'Imeko Afon',
            'Ipokia ',
            'Odeda',
            'Odogbolu',
            'Ogun Waterside',
            'Remo North',
            'Sagamu',
        ]
    ],
    [
        'name'=>'Oyo State',
        'cities'=>[
            'Akinyele',
            'Egbeda',
            'Ibadan',
            'Ido',
            'Oluyole',
            'Afijio',
            'Atiba',                   
            'Atisbo',                    
            'Ayete',                    
            'Eruwa',                    
            'Igbo Ora',                     
            'Irepo',                     
            'Iseyin',                     
            'Itesiwaju',                    
            'Iwajowa',                    
            'Kajola',                     
            'Lagelu',                     
            'Ogbomosho North',                    
            'Ogbomosho South',                     
            'Ogo Oluwa',                    
            'Olorunsogo',                    
            'Ona-Ara',                  
            'Orelope',                    
            'Ori Ire',                     
            'Oyo',                     
            'Saki East',                    
            'Saki West',                   
            'Surulere-Oyo',
        ]
    ],
    [
        'name'=>'Rivers State',
        'cities'=>[
            'Eleme',
            'Ikwerre',
            'Obio-Akpor',
            'Oyigbo',
            'Port-Harcourt',
            'Abua/Odual',  
            'Ahoada',                     
            'Akuku Toru',                     
            'Andoni',                     
            'Asari-Toru',                     
            'Bonny',                     
            'Degema',                     
            'Emohua',                     
            'Etche',                     
            'Gokana',                    
            'Khana',                     
            'Ogba/Egbema/Ndoni',                     
            'Ogu/Bolo',                     
            'Okrika',                     
            'Omuma',                    
            'Tai',
        ]
    ],
    [
        'name'=>'Abia State',
        'cities'=>[
            'Aba North',                       
            'Aba South',                       
            'Umuahia',
            'Arochukwu',                     
            'Bende',                     
            'Ikwuano',                     
            'Isiala Ngwa',                    
            'Isuikwuato',                     
            'Obi Ngwa',                    
            'Ohafia',                     
            'Osisioma Ngwa',                     
            'Ugwunagbo',                     
            'Ukwa',                     
            'Umu Nneochi',
        ]
    ],
    [
        'name'=>'Adamawa State',
        'cities'=>[
            'Yola North',
            'Yola South',
            'Demsa',                  
            'Fufore',                    
            'Ganye',                    
            'Girei',                     
            'Gombi',                   
            'Guyuk',                     
            'Hong',                    
            'Jada',                     
            'Lamurde',                     
            'Madagali',                     
            'Maiha',                     
            'Mayo-Belwa',                     
            'Michika',                    
            'Mubi North',                     
            'Mubi South',                    
            'Numan',                     
            'Shelleng',                     
            'Song',                     
            'Toungo',
        ]
    ],
    [
        'name'=>'Akwa Ibom State',
        'cities'=>[
            'Abak',
            'Eket',
            'Ikot Ekpene',
            'Oron',
            'Uyo',
            'Eastern Obolo',                     
            'Esit-Eket',                     
            'Essien Udim',                     
            'Etim-Ekpo',                     
            'Etinan',                     
            'Ibeno',                   
            'Ibesikpo Asutan',                    
            'Ibiono Ibom',                     
            'Ika',                     
            'Ikono',                    
            'Ikot Abasi',                    
            'Ini',                    
            'Itu',                     
            'Mbo',                     
            'Mkpat Enin',                    
            'Nsit Atai',                    
            'Nsit Ibom',                     
            'Nsit Ubium',                    
            'Obot Akara',                    
            'Okobo',                     
            'Onna',                    
            'Oruk Anam',                    
            'Udung Uko',                   
            'Ukanafun',                    
            'Uquo-Ibeno',                    
            'Uruan',                   
            'Urue-Offong/Oruko',
        ]
    ],
    [
        'name'=>'Anambra State',
        'cities'=>[
           'Awka',
           'Idemili',
           'Nnewi',
           'Onitsha',
           'Aghamelu',                   
           'Aguata',                    
           'Anambra East',                   
           'Anambra West',                   
           'Anaocha',                   
           'Ayamelum',                   
           'Dunukofia',                   
           'Ekwusigo',                   
           'Ihiala',                   
           'Njikoka',                   
           'Ogbaru',                   
           'Orumba',                  
           'Oyi',
        ]
    ],
    [
        'name'=>'Bauchi State',
        'cities'=>[
            'Bauchi LGA',
            'Bogoro',
            'Alkaleri',                   
            'Damban',                    
            'Darazo',                    
            'Dass',                   
            'Gamawa',                    
            'Ganjuwa',                   
            'Giade',                   
            'Itas/Gadau',                   
            "Jama'are",                   
            'Katagum',                    
            'Kirfi',                   
            'Misau',                   
            'Ningi',                   
            'Shira',                   
            'Toro',                   
            'Warji',                   
            'Zaki',
        ]
    ],
    [
        'name'=>'Bayelsa State',
        'cities'=>[
            'Yenagoa',
            'Brass',
            'Ekeremor',
            'Kolokuma/Opokuma',
            'Nembe',
            'Ogbia',
            'Sagbama',
            'Southern Ijaw'
        ]
    ],
    [
        'name'=>'Benue State',
        'cities'=>[
            'Gboko',
            'Katsina-Alam',
            'Makurdi',
            'Otukpo',
            'Ado',                   
            'Agatu',                  
            'Apa',                   
            'Buruku',                  
            'Guma',                  
            'Gwer',                  
            'Konshisha',                  
            'Kwande',                  
            'Logo',                  
            'Obi',                  
            'Ogbadibo',                  
            'Ohimini',                  
            'Oju',                  
            'Okpokwu',                  
            'Tarka',                  
            'Ukum',                 
            'Ushongo',                
            'Vandeikya',           
        ]
    ],
    [
        'name'=>'Borno State',
        'cities'=>[
            'Maiduguri',
            'Abadam',
            'Askira/Uba',
            'Bama',
            'Bayo',
            'Biu',
            'Chibok',
            'Damboa',
            'Dikwa',
            'Gubio',
            'Guzamala',
            'Gwoza',
            'Hawul',
            'Jere',
            'Kaga',
            'Kala/Balge',
            'Konduga',
            'Kukawa',
            'Kwaya Kusar',
            'Mufa',
            'Magumeri',
            'Marte',
            'Mobbar',
            'Monguno',
            'Ngala',
            'Nganzai',
            'Shani'
        ]
    ],
    [
        'name'=>'Cross River State',
        'cities'=>[
            'Calabar',                    
            'Ikom',
            'Ogoja',
            'Abi',                  
            'Akamkpa',                   
            'Akpabuyo',                   
            'Bakassi',                   
            'Bekwara',                   
            'Biase',                    
            'Boki',                   
            'Etung',                   
            'Obanliku',                   
            'Obubra',                   
            'Obudu',                   
            'Odukpani',                    
            'Yakuur',
            'Yala',
        ]
    ],
    [
        'name'=>'Delta State',
        'cities'=>[
            'Oshimili South',
            'Sapele',
            'Ugheli',
            'Uvwie',                       
            'Warri',
            'Aniocha North',                     
            'Aniocha South',                    
            'Bomadi',                    
            'Burutu',                     
            'Ethiope East',                     
            'Ethiope West',                    
            'Ika North East',                    
            'Ika South',                    
            'Isoko',                     
            'Ndokwa East',                    
            'Ndokwa West',                    
            'Okpe',                    
            'Oshimili North',                     
            'Patani',                     
            'Udu',                     
            'Ukwuani',
        ]
    ],
    [
        'name'=>'Ebonyi State',
        'cities'=>[
            'Abakaliki',                    
            'Afikpo North',                 
            'Afikpo South',                   
            'Ebonyi',                   
            'Ezza',                   
            'Ikwo',                   
            'Ishielu',                    
            'Ivo',                  
            'Izzi',                    
            'Ohaozara',                   
            'Ohaukwu',                   
            'Onicha'
        ]
    ],
    [
        'name'=>'Edo State',
        'cities'=>[
            'Benin City',
            'Egor',
            'Ekpoma',
            'Ikpoba-Okha',
            'Okada',
            'Akoko-Edo',                   
            'Auchi',                    
            'Esan North East',                     
            'Fugar',                   
            'Igueben',                 
            'Irrua',                  
            'Orhionmwon',                    
            'Ovia South',              
            'Owan',                    
            'Ubiaja',                   
            'Uhunmwonde',
        ]
    ],
    [
        'name'=>'Ekiti State',
        'cities'=>[
            'Ado Ekiti',                   
            'Ido-Osi',                    
            'Ikere',                    
            'Ikole',
            'Ilawe',
            'Aiyekire (Gbonyin)',                   
            'Aramoko',                    
            'Efon ',                  
            'Emure',                   
            'Ijero',                   
            'Ilejemeje',                   
            'Irepodun/Ifelodun',                    
            'Ise/Orun',                   
            'Moba',                   
            'Omuo',                   
            'Oye',
        ]
    ],
    [
        'name'=>'Enugu State',
        'cities'=>[
            'Enugu / Enugu',
            'Nkanu West',
            'Nsukka',                   
            'Udi',    
            'Aninri',                    
            'Awgu',                    
            'Ezeagu',                    
            'Igbo Eze South',                     
            'Igbo-Etiti',                     
            'Igbo-Eze North',                   
            'Isi-Uzo',                   
            'Nkanu East',                   
            'Oji-River',                  
            'Udenu',                  
            'Uzo-Uwani',
        ]
    ],
    [
        'name'=>'Gombe State',
        'cities'=>[
            'Gombe LGA',
            'Akko',
            'Balanga',
            'Billiri',
            'Dukku',
            'Funakaye',
            'Kaltungo',
            'Kwami',
            'Nafada',
            'Shomgom',
            'Yamaltu/Deba'
        ]
    ],
    [
        'name'=>'Imo State',
        'cities'=>[
            'Ikeduru',
            'Mbaitoli',
            'Okigwe',                    
            'Orlu',                   
            'Owerri',    
            'Aboh-Mbaise',                    
            'Ahiazu-Mbaise',                    
            'Ehime-Mbano',                    
            'Ezinihitte',                   
            'Ezinihitte Mbaise',                    
            'Ideato North',                   
            'Ideato South',                   
            'Ihitte/Uboma',                   
            'Isiala Mbano',                   
            'Isu',                   
            'Ngor-Okpala',                   
            'Njaba',                
            'Nkwerre',                 
            'Nwangele',                  
            'Obowo',                 
            'Oguta',                  
            'Ohaji/Egbema',               
            'Onuimo',                
            'Orsu',             
            'Oru',
        ]
    ],
    [
        'name'=>'Jigawa State',
        'cities'=>[
            'Dutse-Jigawa',                   
            'Garki',
            'Auyo',                     
            'Babura',                    
            'Biriniwa',                   
            'Buji',                   
            'Gagarawa',                    
            'Gumel',                    
            'Guri',                    
            'Gwaram',                    
            'Gwiwa',                  
            'Hadejia',                   
            'Jahun',                    
            'Kafin Hausa',
            'Kaugama',                    
            'Kazaure',                    
            'Kiri Kasamma',                   
            'Kiyawa',                   
            'Maigatari',                    
            'Malam Madori',                  
            'Miga',                 
            'Ringim',                
            'Roni',                    
            'Sule-Tankarkar',                   
            'Taura',                    
            'Yankwashi',
        ]
    ],
    [
        'name'=>'Kaduna State',
        'cities'=>[
            'Chikun',
            'Igabi',
            'Kaduna / Kaduna State',
            'Zaria',                
            'Birnin-Gwari',                    
            'Giwa',                 
            'Ikara',               
            'Jaba',                 
            "Jema'a",           
            'Kachia',                 
            'Kagarko',                 
            'Kajuru',              
            'Kaura-Kaduna',                
            'Kauru',                    
            'Kubau',                 
            'Kudan',              
            'Lere',               
            'Makarfi',           
            'Sanga',    
            'Soba',
            'Zango-Kataf',
        ]
    ], 
    [
        'name'=>'Kano State',
        'cities'=>[
            'Fagge',
            'Kano Municipal',
            'Nasarawa-Kano',
            'Tarauni',
            'Ajingi',                   
            'Albasu',                   
            'Bagwai',                   
            'Bebeji',                 
            'Bichi',                  
            'Bunkure',                   
            'Dala',                 
            'Dambatta',                
            'Dawakin Kudu',                
            'Dawakin Tofa',                 
            'Doguwa',             
            'Gabasawa',                
            'Garko',      
            'Garum Mallam',           
            'Garun Mallam',          
            'Gaya',                 
            'Gezawa',                
            'Gwale',                 
            'Gwarzo',               
            'Kabo',             
            'Karaye',            
            'Kibiya',            
            'Kiru',            
            'Kumbotso',            
            'Kunchi',          
            'Kura',               
            'Madobi',            
            'Makoda',          
            'Minjibir',          
            'Rano',                   
            'Rimin Gado',                   
            'Rogo',                 
            'Shanono',                   
            'Sumaila',                   
            'Takai',                   
            'Tofa',                   
            'Tsanyawa',                
            'Tudun Wada',                
            'Ungogo',                
            'Warawa',                 
            'Wudil',
        ]
    ],
    [
        'name'=>'Katsina State',
        'cities'=>[
            'Danja',                    
            'Daura',                    
            'Katsina',                     
            'Zango',
            'Bakori',                    
            'Batagarawa',                   
            'Batsari',                    
            'Baure',                   
            'Bindawa',                   
            'Charanchi',                   
            'Dan Musa',                    
            'Dandume',                  
            'Dutsi',                  
            'Dutsin-Ma',                
            'Faskari',                  
            'Funtua',                   
            'Ingawa',                   
            'Jibia',                  
            'Kafur',                  
            'Kaita',                  
            'Kankara',                   
            'Kankia',                  
            'Kurfi',                
            'Kusada',                 
            "Mai'adua",               
            'Malumfashi',                   
            'Mani',                   
            'Mashi',                 
            'Matazu',               
            'Musawa',                  
            'Rimi',                   
            'Sabuwa',                  
            'Safana',                  
            'Sandamu',
        ]
    ],
    [
        'name'=>'Kebbi State',
        'cities'=>[
            'Birnin Kebbi',                     
            'Jega',                    
            'Zuru',
            'Aleiro',                     
            'Arewa-Dandi',                    
            'Argungu',                   
            'Augie',                   
            'Bagudo',                   
            'Bunza',                   
            'Dandi',                    
            'Fakai',                    
            'Gwandu',                 
            'Kalgo',                   
            'Koko/Besse',                   
            'Maiyama',                   
            'Ngaski',                   
            'Sakaba',                   
            'Shanga',                   
            'Suru',                   
            'Wasagu/Danko',                  
            'Yauri',
        ]
    ],
    [
        'name'=>'Kogi State',
        'cities'=>[
            'Lokoja',
            'Okene',      
            'Adavi',                   
            'Ajaokuta',                    
            'Ankpa',                   
            'Bassa',                   
            'Dekina',                  
            'Ibaji',                   
            'Idah',                  
            'Igala Mela',                
            'Igalamela-Odolu',               
            'Ijumu',                 
            'Kabba/Bunu',              
            'Kogi LGA',                
            'Koton Karfe',                
            'Mopa-Muro',              
            'Ofu',              
            'Ogori/Magongo',              
            'Okehi',                 
            'Olamaboro',                
            'Omala',          
            'Yagba East',          
            'Yagba West',
        ]
    ],
    [
        'name'=>'Kwara State',
        'cities'=>[
            'Ilorin East',
            'Ilorin South',
            'Ilorin West',
            'Asa',
            'Baruten',
            'Edu',
            'Ekiti-Kwara',
            'Ifelodun-Kwara',
            'Irepodun-Kwara',
            'Isin',
            'Kaiama',
            'Moro',
            'Offa',
            'Oke-Ero',
            'Oyun',
            'Pategi'
        ]
    ],
    [
        'name'=>'Nasarawa State',
        'cities'=>[
            'Karu-Nasarawa',
            'Keffi',
            'Lafia',
            'Akwanga',
            'Awe',
            'Doma',
            'Keana',
            'Kokona',
            'Nasarawa',
            'Nasarawa-Eggon',
            'Obi-Nasarawa',
            'Toto',
            'Wamba'
        ]
    ],
    [
        'name'=>'Niger State',
        'cities'=>[
            'Bida',
            'Bosso',
            'Chanchaga',
            'Minna',
            'Suleja',
            'Agaie',
            'Agwara',
            'Borgu',
            'Edati',
            'Gbako',
            'Gurara',
            'Katcha',
            'Kontagora',
            'Lapai',
            'Lavun',
            'Magama',
            'Mariga',
            'Mashegu',
            'Mokwa',
            'Muya',
            'Paikoro',
            'Rafi',
            'Rijau',
            'Shiroro',
            'Tafa',
            'Wushishi'
        ]
    ],
    [
        'name'=>'Ondo State',
        'cities'=>[
            'Akure',
            'Iju/Itaogbolu',
            'Okitipupa',
            'Ondo / Ondo State',
            'Owo',
            'Akungba',
            'Ese-Odo',
            'Idanre',
            'Ifedore',
            'Ikare Akoko',
            'Ilaje',
            'Ile-Oluji-Okeigbo',
            'Irele',
            'Isua',
            'Odigbo',
            'Oka',
            'Okeagbe',
            'Okeigbo',
            'Ose'
        ]
    ],
    [
        'name'=>'Osun State',
        'cities'=>[
            'Ede',
            'Ife',                     
            'Ilesa',                    
            'Olorunda-Osun',                   
            'Osogbo',                    
            'Aiyedade',                    
            'Aiyedire',                    
            'Atakumosa East',                    
            'Atakumosa West',                    
            'Boluwaduro',                     
            'Boripe',                 
            'Egbedore',                   
            'Ifedayo',                  
            'Ifelodun-Osun',                   
            'Ila',                    
            'Irepodun-Osun',            
            'Irewole',              
            'Isokan',                   
            'Iwo',                 
            'Obokun',                   
            'Ola-Oluwa',                  
            'Oriade',                  
            'Orolu',
        ]
    ],
    [
        'name'=>'Plateau State', 
        'cities'=>[
            'Jos',
            'Barkin Ladi',
            'Bassa-Plateau',                    
            'Bokkos',                    
            'Kanam',                   
            'Kanke',                   
            'Langtang North',                    
            'Langtang South',                     
            'Mangu',                    
            'Mikang',                   
            'Pankshin',                   
            'Quaan Pan',                    
            'Riyom',                    
            'Shendam',                   
            'Wase',
        ]
    ],
    [
        'name'=>'Sokoto State',
        'cities'=>[
            'Illela',                     
            'Sokoto North',
            'Sokoto South',
            'Binji',                     
            'Bodinga',                     
            'Dange-Shuni',                    
            'Gada',                     
            'Goronyo',                     
            'Gudu LGA',                   
            'Gwadabawa',                   
            'Isa',                    
            'Kebbe',                    
            'Kware',                    
            'Rabah',                    
            'Sabon Birni',                     
            'Shagari',                     
            'Silame',                     
            'Tambuwal',                     
            'Tangaza',                     
            'Tureta',                    
            'Wamako',                    
            'Wurno',                    
            'Yabo',
        ]
    ],
    [
        'name'=>'Taraba State',
        'cities'=>[
            'Jalingo',                    
            'Takum',                     
            'Wukari',
            'Ardo-Kola',                    
            'Bali',                     
            'Donga',                     
            'Gashaka',                     
            'Gassol',                    
            'Ibi',                    
            'Karim-Lamido',                   
            'Kurmi',                    
            'Lau',                    
            'Sardauna',                   
            'Ussa',                    
            'Yorro',                  
            'Zing',
        ]
    ],
    [
        'name'=>'Yobe State',
        'cities'=>[
            'Damaturu',                    
            'Potiskum',
            'Bade',                     
            'Bursari',                    
            'Fika',                    
            'Fune',                     
            'Geidam',                     
            'Gujba',                    
            'Gulani',                    
            'Jakusko',                     
            'Karasuwa',                    
            'Machina',                    
            'Nangere',                    
            'Nguru',                    
            'Tarmua',                     
            'Yunusari',                    
            'Yusufari',
        ]
    ],
    [
        'name'=>'Zamfara State',
        'cities'=>[
            'Gusau',
            'Anka',                    
            'Bakura',                   
            'Birnin Magaji',                    
            'Bukkuyum',                    
            'Bungudu',                   
            'Gummi',                  
            'Kaura Namoda',                   
            'Maradun',                    
            'Maru',                   
            'Shinkafi',                    
            'Talata Mafara',                 
            'Tsafe',                 
            'Zurmi',
        ]
    ]

 ];
?>